### ISSUE TITLE
Some tests fail

### ISSUE THREAD

**Issue by Razican** [NTRUOpenSourceProject/NTRUMLS#1]
I just downloaded the repo in my Linux x86_64 laptop and I get some failing tests:

```
PACK: testing parameter set xxx-20140508-401
signatures not equal @ indx 195 :: isig -131072 osig 262144 sp 1
KEYGEN: testing parameter set xxx-20140508-401
SUITE: Testing parameter set xxx-20140508-401
	 fail
signatures not equal @ indx 386 :: isig -32768 osig 65536 sp 1
KEYGEN: testing parameter set xxx-20151024-443
SUITE: Testing parameter set xxx-20151024-443
	 fail
PACK: testing parameter set xxx-20151024-563
signatures not equal @ indx 74 :: isig -32768 osig 65536 sp 1
KEYGEN: testing parameter set xxx-20151024-563
SUITE: Testing parameter set xxx-20151024-563
	 fail
```

Is this normal?

**Comment by jschanck-si** [comment]
No, definitely not normal. Looks like it might be compiler-dependent. Can you tell me which compiler you're using and the version?

**Comment by Razican** [comment]
I'm using `gcc version 5.3.1 20160406 (Red Hat 5.3.1-6) (GCC)` on Fedora 23 x86_64.

**Comment by jschanck-si** [comment]
Just a problem w/ the test code. We were testing the signature compression and decompression routines on random data instead of real signatures. Turns out there's an edge case for random data that never happens for real signatures. Thanks for the report.
